### ISSUE TITLE
Melhorar os arquivos dockerfile e docker-compose

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#100]
## Tasks:
- [x] Usar variáveis de ambiente
- [x] Usar `requirements.txt` no arquivos dockerfile
- [x] Atualizar `.gitignore`

## Critérios de Aceitação:
- [x] Aceitação de todos os Devops
