### ISSUE TITLE
Criação do discord do projeto de ChatBot

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#101]
## Descrição da Issue
Criação de um discord para as equipes plus ultra, capivaras e slowbros poderem trabalhar na disciplina com mais transparência e com intuito de melhorar a comunicação entre as equipes.

## Tasks:
- [x] Criar o servidor.
- [x] Arrumar o servidor.
- [x] Mandar o link para que todos entrem.

## Critérios de Aceitação:
- [x] Servidor do agrado de todos.
- [x] Todos os integrantes de todas as equipes no discord com o devido cargo.
