### ISSUE TITLE
Documentação das sprints 4 e 5

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#102]
## Descrição da Issue
Fazer a documentação dos resultados da sprint 4 e do planejamento da sprint 5

## Tasks:
- [x] Documentação dos resultados da sprint 4.
- [x] Documentação do planejamento da sprint 5.
- [x] Commitar na branch plusultra.
- [x] Mandar para a main.

## Critérios de Aceitação:
- [x] Documentos bem estruturados.
- [x] Revisão de alguém da equipe.
