### ISSUE TITLE
Reunião para definir as US

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#104]
## Descrição da Issue
Deve-se finalizar o backlog

## Tasks:
- [x] Desenvolver mais features
- [x] Desenvolver as histórias de usuário

## Critérios de Aceitação:
- [x] Aprovação por alguém de fora
