### ISSUE TITLE
Como contribuir

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#107]
## Descrição da Issue
Elaborar a parte do readme que discorre sobre como contribuir no projeto.

## Tasks:
- [x] Guia de Contribuição
- [x] Código de Conduta
- [ ] #117
- [x] Políticas de Contribuição
- [x] Template para criação de issues
- [x] Template para criação de pull requests

## Critérios de Aceitação:
- [x] Tarefa total ou parcialmente concluída

**Comment by gatotabaco** [comment]
[Template para criação de Issues](https://github.com/fga-eps-mds/2021-1-Bot/blob/main/.github/ISSUE_TEMPLATE/custom.md)

**Comment by gatotabaco** [comment]
[Template para pull request](https://github.com/fga-eps-mds/2021-1-Bot/blob/main/.github/pull_request_template.md)

**Comment by gatotabaco** [comment]
[Como contribuir](https://github.com/fga-eps-mds/2021-1-Bot/blob/main/docs/contribuir.md)

**Comment by gatotabaco** [comment]
[Código de conduta](https://github.com/fga-eps-mds/2021-1-Bot/blob/main/docs/conduta.md) 

Esse documento não está completo pois faltam alguns pequenos ajustes em questões que devem ser discutidas coletivamente, relativas a aplicações das regras do servidor.

**Comment by gatotabaco** [comment]
Issue fechada e uma nova issue foi gerada para resolver o guia de instalação.

https://github.com/fga-eps-mds/2021-1-Bot/issues/117
