### ISSUE TITLE
Disponibilizar o tutorial Rasa & Telegram aos demais tecnologistas

### ISSUE THREAD

**Issue by DouglasMonteles** [fga-eps-mds/2021-1-Bot#114]
## Tutorial Rasa & Telegram
Disponibilizando o tutorial que está na branch rasa-training para os demais tecnologistas junto com dois vídeos onde explico o passo-a-passo do tutorial de xomo integrar o projeto Rasa com o Telegram e falo sobre o NgRok.

## Tasks:
- [x] Tutorial Rasa & Telegram
- [x] NgRok

## Critérios de Aceitação:
- [x] Ser visualizado por todos os tecnologistas
- [x] Não deixar nenhuma dúvida
