### ISSUE TITLE
Sugestão de melhoria no template de pull request

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#134]
## Tasks:
- [x] Corrigir erros de ortografia
- [x] Mudar links na parte de close. É só digitar `#` e o github jé entende que se deseja linkar uma issue.
- [x] Acrescentar comentários falando que é pra apagar as checkboxes que não serão marcadas (a issue final fica menos poluída)
