### ISSUE TITLE
Reunião de pre-planning da sprint 6

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#136]
## Descrição da Issue
Reunião para dividir as tasks a serem feitas entre os grupos para depois serem divididas entre os integrantes.

## Tasks:
- [x] Ver o que foi feito na sprint
- [x] Determinar o que falta fazer
- [x] Distribuir tarefas

## Critérios de Aceitação:
- [x] Tarefas bem distribuídas e acordadas pelos presentes na reunião
