### ISSUE TITLE
Estudar sobre o deploy do projeto Rasa no Heroku

### ISSUE THREAD

**Issue by DouglasMonteles** [fga-eps-mds/2021-1-Bot#141]
## Estudar sobre o deploy do Rasa
Iniciar os estudos e procedimentos para realizar o deploy do Rasa no Heroku

## Tasks:
- [x] Criar os arquivos docker necessários
- [x] Criar os arquivos de configuração do Heroku
- [x] Deploy manual do projeto no Heroku
