### ISSUE TITLE
Revisar a descrição e o documento de arquitetura

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#147]
## Descrição da Issue
Revisar a descrição e o documento de arquitetura e sugerir possíveis mudanças

## Tasks:
- [x] Revisar a descrição
- [x] Sugerir possíveis mudanças, se preciso
- [x] Revisar o documento de arquitetura
- [x] Sugerir possíveis mudanças, se preciso

## Critérios de Aceitação:
- [x] Descrição revisada
- [ ] Documento de arquitetura revisado
