### ISSUE TITLE
Documentações das sprints

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#149]
## Descrição da Issue
Documentar as todas as sprints até a realease 1

## Tasks:
- [ ] Planejamento de todas as sprints
- [ ] Resultados de todas as sprints

## Critérios de Aceitação:
- [ ] Documento revisado por, pelo o menos, 1 pessoa do grupo Slowbros
