### ISSUE TITLE
Otimização da GH Page

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#150]
## Descrição da Issue
Issue com o objetivo de melhorar a página do projeto, a fim de otimizá-la e melhorar a experiência do usuário.

## Tasks:
- [x] Melhorias na navegação
- [x] Colocar a logo
- [x] Paleta de cores no site

## Critérios de Aceitação:
- [x] A página possui uma melhor navegação
- [x] SIte possui a logo
- [x] Mudanças na paleta de cores
