### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#154]
## Descrição da Issue
Iniciar o roadmap.

## Tasks:
- [x] Fazer um modelo para o roadmap;
- [x] Fazer o roadmap até a sprint 5 - 6.

## Critérios de Aceitação:
- [x] Aprovação da equipe

**Comment by PedroLSF** [comment]
#Descrição
Foi feita uma reunião para a coleta das sprints das equipes como um individual

**Comment by AnaCarolinaRodriguesLeite** [comment]
O roadmap foi mapeado conforme as atividades das issues correspondentes ao grupo todo, documentando no template escolhido no modelo do miro e arquivando fora da main. Ao final foi feita uma pequena reunião para que pudessemos organizar os pontos finais e mandar para PR.
