### ISSUE TITLE
Integrar funcionalidades da  FT03: Transmissão e prevenção ao bot

### ISSUE THREAD

**Issue by Ericklevy** [fga-eps-mds/2021-1-Bot#162]
## Descrição da Issue
Integrar funcionalidades da  FT03: Transmissão e prevenção ao bot

## Tasks:
- [x] US07   @Ericklevy 
- [x] US08  @DouglasMonteles 
- [x] US09   @kayrocesar 
- [x] US10   @LamequeFernandes 
- [x] US11   @LamequeFernandes 
- [x] US12   Não e possivel por agora
- [x] US13   Não e possivel por agora

## Critérios de Aceitação:
- [ ] Revisão de pelo menos um membro de cada equipe

**Comment by DouglasMonteles** [comment]
Vou começar a implementar a task **US08**
