### ISSUE TITLE
Adicionar informações da Sprint do Time Plus Ultra

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#163]
## Descrição da Issue
A issue tem como objetivo adicionar as informações referentes ao Time Plus Ultra tanto da Sprint 5 quanto da Sprint 6 ao GH Page, assim como pequenas alterações feitas no doc. de arquitetura.

## Tasks:
- [ ] Adicionar informações das duas Sprints
- [ ] Adicionar alterações no doc. de arquitetura

## Critérios de Aceitação:
- [ ] Ambas alterações foram feitas na Page
