### ISSUE TITLE
Buscar por monitores pra feedback dos documentos

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [fga-eps-mds/2021-1-Bot#167]
## Descrição da Issue
Busca por monitores para dar um feedback sobre os documentos realizados no projeto.

## Tasks:
- [x] Conversar com o monitor.
- [x] Receber o feedback.
- [x] Notificar o grupo sobre o feedback.

## Critérios de Aceitação:
- [x] Ter a conversa com o monitor.
- [x] Ter recebido o feedback.

**Comment by AnaCarolinaRodriguesLeite** [comment]
Foi pedido o feedback a respeito dos documentos já feitos e como eles estariam. A partir disso, o monitor me passou um PDF sobre o que falta ou como está o documento ou que precisa de mudança. Com isso, conseguimos rever erros que deixamos passar mesmo fazendo PR de mais de uns membros. O feedback foi bastante construtivo, descrevendo os erros, mudanças, pontos legais ou negativos e situações de mudanças rápidas, até mesmo de documentos incompletos.
