### ISSUE TITLE
Finalização da GH Page para R1

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#176]
## Descrição da Issue
A issue tem o objetivo de finalizar tudo o que falta na GH Page para a Release 1.

## Tasks:
- [x] Todas as documentações na página
- [ ] Página inicial alterada

## Critérios de Aceitação:
- [x] GH Page finalizada
