### ISSUE TITLE
Correção de erros no documento de arquitetura

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#182]
## Descrição da Issue
A partir do feedback de revisão feita no documento de arquitetura, fazer as alterações necessárias e checar possíveis outros erros.

## Tasks:
- [x] Fazer as alterações
- [x] Revisão do documento

## Critérios de Aceitação:
- [x] Documento alterado, revisado e atualizado.
