### ISSUE TITLE
Documentação das sprints

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#188]
## Descrição da Issue
[Descrever de forma sucinta a issue, colocando quaisquer informações necessárias para a realização da mesma.]
Documentar as sprints 6 e 7.

## Tasks:
- [x] Documentar os resultados da sprints 6
- [x] Documentar o planejamento da sprints 7

## Critérios de Aceitação:
- [x] Commitar os documentos
