### ISSUE TITLE
Reunião acerca dos vídeos de apresentação

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#191]
## Descrição da Issue
Reunião acerca dos vídeos de apresentação, onde decidiremos sobre os roteiros, horários e quem vai apresentar.

## Tasks:
- [x] Refinar o roteiro geral
- [x] Disponibilizar para a @klmurussi 
- [x] Disponibilizar o roteiro das equipes no grupo do telegram

## Critérios de Aceitação:
- [x] Todos estarem satisfeitos com os roteiros
