### ISSUE TITLE
Correção no doc de Identidade Visual

### ISSUE THREAD

**Issue by klmurussi** [fga-eps-mds/2021-1-Bot#194]
## Descrição da Issue
Corrigir erros apontados pelos colegas no documento de Identidade Visual

## Tasks:
- [x] Correção do nome do chatbot
- [x] Mudança do termo "bot" para "chatbot"
- [x] Padrão ABNT nas referências

## Critérios de Aceitação:
- [ ] Revisão aceita por outra pessoa

**Comment by klmurussi** [comment]
As duas primeiras tasks corrigidas pela @AnaCarolinaRodriguesLeite
