### ISSUE TITLE
Correção no doc de Personalidade-do-bot

### ISSUE THREAD

**Issue by klmurussi** [fga-eps-mds/2021-1-Bot#197]
## Descrição da Issue
Fazer as correções apontadas pelos outros integrantes.

## Tasks:
- [x] Título do Histórico
- [x] Documento de Introdução
- [x] Padrão ABNT nas referências

## Critérios de Aceitação:
- [ ] Revisão aceita por outra pessoa
