### ISSUE TITLE
Ajustar a parte de issues no Guia de Contribuição

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#215]
## Descrição da Issue
As orientações relativas a issues nesse documento estão equivocadas. É necessário apagar a parte que fala sobre aguardar issue ser aprovada e linkar uma orientação do código de conduta. Além de deixar mais claro os critérios para pontuação das issues.

## Tasks:
- [x] Ajustar as orientações de criação de Issue
- [x] Definir critérios para a estimate

## Critérios de Aceitação:
- [x] Orientações ajustadas de modo correto segundo o que foi colocado na descrição

**Comment by gatotabaco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/215?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @klmurussi @LamequeFernandes @Thais-ra
