### ISSUE TITLE
Web scraping

### ISSUE THREAD

**Issue by DouglasMonteles** [fga-eps-mds/2021-1-Bot#216]
## Descrição da Issue
Faz-se necessário pegar a UF e a Cidade informadas pelo usuário através do telegram e utilizar um web scraping que, com base nestes parâmetros, fará uma busca no site do governo https://qsprod.saude.gov.br/extensions/covid-19_html/covid-19_html.html para obter os dados sobre a covid

## Tasks:
- [x] Pegar a UF e a Cidade informados pelo usuário
- [x] Utilizar um web scraping para obter os dados
- [x] Devolver uma resposta para o usuário

**Comment by yudi-azvd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/216?planning-poker) with ZenHub @AmandaNbr @DouglasMonteles @PedroLSF @victorear05

**Comment by DouglasMonteles** [comment]
Tentei resumir todo o progresso feito até agora [neste vídeo](https://youtu.be/wXeSAyHs6Bk) onde demonstro como o web scraping em python funciona integrado ao Rasa Chatbot para obter os dados sobre covid-19 de uma determinada cidade.

**Comment by kayrocesar** [comment]
> Tentei resumir todo o progresso feito até agora [neste vídeo](https://youtu.be/wXeSAyHs6Bk) onde demonstro como o web scraping em python funciona integrado ao Rasa Chatbot para obter os dados sobre covid-19 de uma determinada cidade.

Muito bom @DouglasMonteles

**Comment by DouglasMonteles** [comment]
Apesar os resultados promissores demonstrados no vídeo, eu cheguei a conclusão de que o web scraping não é rápido o suficiente para o Rasa, isso por que o web scraping precisa carregar a página web, acessar o campo de uf e de cidades, pesquisar a uf e cidade informada pelo usuário, esperar os dados carregarem e pegar as informações sobre o covid daquela cidade leva, na melhor das hipóteses, uns 20s, e as ações customizadas do Rasa devem dar uma resposta em, no máximo, 10s, caso contrário, uma exceção de timeout é informada e o bot para de responder.  

No entanto, nesta issue, eu consegui criar um formulário onde o usuário pode informar a uf e a cidade, onde estas são armazenadas em slots (pense em slots como variáveis do Rasa), e ficam disponíveis para serem usadas em respostas ou em ações customizadas.

**Comment by gatotabaco** [comment]
@DouglasMonteles @yudi-azvd @AmandaNbr @PedroLSF @victorear05 alterem a estimate para alguma dentro dos padrões combinados em reunião. 21 está fora
