### ISSUE TITLE
Arquivos csv com python nas actions

### ISSUE THREAD

**Issue by Ericklevy** [fga-eps-mds/2021-1-Bot#217]
## Descrição da Issue
Utilizar arquivos .CSV para obter informações sobre o Covid-19 e integra-los em ações customizadas no Chatbot

## Tasks:
- [ ] Encontrar uma fonte confiável para os arquivos .csv
- [ ] Percorrer as informações de um .csv dentro de uma action customizada
- [ ] Obter somente as informações relacionadas a uma intent 
- [ ] Devolver uma resposta composta com informações obtidas dos .csv

**Comment by yudi-azvd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/217?planning-poker) with ZenHub @AmandaNbr @PedroLSF @DouglasMonteles @victorear05

**Comment by DouglasMonteles** [comment]
Este site fornece arquivos .CSV que são atualizados todo dia
https://covid.saude.gov.br/

**Comment by Thais-ra** [comment]
Quais tipos de informações sobre covid-19 voces estão procurando nessa issue?

**Comment by DouglasMonteles** [comment]
A priori, seria a quantidade de infectados por covid na minha cidade/país, onde usaríamos o .csv como uma base de dados para fazer a pesquisa, mas dependendo do csv, poderiam ser informações sobre o número de óbitos, de casos recuperados, etc

**Comment by DouglasMonteles** [comment]
Segue uma demonstração de como está funcionando a pesquisa por dados do covid usando arquivos .csv através do chat do Rasa: 
https://www.youtube.com/watch?v=3YKoK3XEOzw

**Comment by DouglasMonteles** [comment]
Vou atualizar o milestone, esta issue vai continuar para a próxima sprint
