### ISSUE TITLE
Documentar sprints

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#220]
## Descrição da Issue
Documentar os resutados da sprint 7 e o planejamento da 8

## Tasks:
- [x] Documentar os resutados da sprint 7
- [x] Documentar o planejamento da sprint 8

## Critérios de Aceitação:
- [x] Bons documentos commmitados

**Comment by AmandaNbr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/220?planning-poker) with ZenHub @DouglasMonteles @Ericklevy @PedroLSF @victorear05 @yudi-azvd
