### ISSUE TITLE
Update no doc. de arquitetura

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#228]
## Descrição da Issue
[Descrever de forma sucinta a issue, colocando quaisquer informações necessárias para a realização da mesma.]

## Tasks:
- [x] Corrigir fluxo de arquitetura
- [x] Adicionar diagrama de casos de uso

## Critérios de Aceitação:
- [x] Fluxo de arquitetura corrigido
- [x] Diagrama de casos de uso adicionado

**Comment by victorear05** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/228?planning-poker) with ZenHub @klmurussi @matheusrazor
