### ISSUE TITLE
Estruturar GitHub Pages com jekyll

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#229]
## Descrição da Issue
Estruturar GitHub Pages com jekyll para automatizar documetações do site.

## Tasks:
- [ ] Menus organizados
- [ ] Identidade visual implementada
- [ ] Documentações atualizadas

## Critérios de Aceitação:
- [ ] Tudo no Jekyll
- [ ] Membros aceitarem as mudanças

**Comment by LamequeFernandes** [comment]
@yudi-azvd já pesquisou e implementou boa parte da base para o gh-pg com jekyll.

**Comment by yudi-azvd** [comment]
Falta linkar a PR pra essa issue
