### ISSUE TITLE
Reunião de pre-planning da sprint 9

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#237]
## Descrição da Issue
Reunião para atribuir tarefas a serem feitas para a sprint 9
## Tasks:
- [x] Determinar o que precisa ser feito
- [x] Atribuir aos grupos 

## Critérios de Aceitação:
- [x] Tarefas bem distribuídas

**Comment by HenriqueHida** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021-1-Bot/237?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @PedroLSF

**Comment by HenriqueHida** [comment]
E assim foram atribuídas as tarefas da sprint 9
![image](https://user-images.githubusercontent.com/78568172/134434919-7697dd39-6ec9-49c7-9fee-5e525b08e46a.png)
