### ISSUE TITLE
Documentação sprints 8 e 9

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#243]
## Descrição da Issue
Criar e melhorar as documentações das sprints 8 e 9

## Tasks:
- [x] Planejamento sprint 8 (melhorar)
- [x] Resultados sprint 8 (Criar)
- [x] Planejamento sprint 9 (Criar)

## Critérios de Aceitação:
- [x] Bons documentos commitados
