### ISSUE TITLE
Configurar ambiente e estudo do Rasa

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#250]
## Descrição da Issue
Configurar ambiente de desenvolvimento do Bot e  assistir ao [dojô de Rasa](https://www.youtube.com/watch?v=O4x1XRHezBY) para todos iniciarem as implementações das US
## Tasks:
- [x] Configurar ambiente de desenvolvimento
- [x] Assistir ao dojô

## Critérios de Aceitação:
- [x] Ambiente configurado
- [x] Básico do Rasa aprendido

**Comment by HenriqueHida** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021-1-Bot/250?planning-poker) with ZenHub @AmandaNbr @gatotabaco

**Comment by gatotabaco** [comment]
@HenriqueHida tira o final estimate, por causa dele a gente não consegue votar

**Comment by HenriqueHida** [comment]
> @HenriqueHida tira o final estimate, por causa dele a gente não consegue votar

Desculpa, votei no lugar errado =x
