### ISSUE TITLE
Instalação e começo de implementação

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#265]
## Descrição da Issue
Estudo sobre Rasa e instalação através do ReadME

## Tasks:
- [x] Ter feito a instalação através do ReadME
- [x] Visto a aula de Rasa

## Critérios de Aceitação:
- [ ] Ter instalado
- [x] Começar a implementar alguma US
