### ISSUE TITLE
Reunião planejamento sprint 10

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#269]
## Descrição da Issue
Reunião para atribuição de tarefas da sprint 10

## Tasks:
- [x] Determinar o que precisa ser feito
- [x] Distribuir tarefas entre os grupos 

## Critérios de Aceitação:
- [x] Tarefas bem distribuídas

**Comment by HenriqueHida** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021-1-Bot/269?planning-poker) with ZenHub @AmandaNbr @gatotabaco
