### ISSUE TITLE
Reunião de brainstorm para possíveis escopos do produto

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#27]
## Fazer uma reunião de brainstorm para os possíveis escopos que o produto pode abranger. 

Isso é necessário pois o grupo compreendeu que a proposta do que deve ser o produto ainda está muito em aberto, portanto, serão definidas algumas propostas, que serão levadas em forma de rascunho de projeto para o cliente. Essa reunião será feita utilizando alguma ferramenta que será sugerida pela @Thais-ra e terá a presença de todos os membros.

## Tasks:
- [x] Definir a ferramenta a ser utilizada
- [x] Reunião com presença de todos os membros
- [x] Levar os possíveis escopos para os outros grupos

**Comment by Thais-ra** [comment]
Para o toró de ideias utilizamos a ferramenta Miro:
https://miro.com/welcome/QXhvOFZEdUlVR1hpRjhaeG01NUlRV2Niekt4RmZ1aTUxdk03Tld5ZnZSZHB4UkZqYXk1V2lOazYwMkdLdnRieHwzMDc0NDU3MzYyMTg2NzY2MTc1

**Comment by Thais-ra** [comment]
![image](https://user-images.githubusercontent.com/35047444/128363024-f3fc17cc-c16d-4c04-ba55-81724639ec10.png)

**Comment by Thais-ra** [comment]
![image](https://user-images.githubusercontent.com/35047444/128363246-35084dea-8fb0-4503-bf8d-deadaa931ae9.png)

**Comment by Thais-ra** [comment]
Membros do grupo que compareceram:
@AnaCarolinaRodriguesLeite 
@gatotabaco 
@LamequeFernandes 
@MegahNevel 
@Thais-ra 

Foi realizado uma votação e o grupo optou por levar 3 temas para o cliente validar, são eles:
- Vacinação
- Perguntas gerais
- Contágio

**Comment by AnaCarolinaRodriguesLeite** [comment]
A reunião com o grupo dos PO's foi realizada por meio do telegram, apontando todas as discussões apontadas na presente reunião. Discutindo também algumas dúvidas que os outros PO's teriam para pode levar ao cliente e sanar todas, trazendo de fato os escopos fechados para os 3 grupos. Nessa conversa, envolveu também a interação de uma dúvida ainda pertinente sobre como seria aplicada as funcionalidades a cada time, especulando todas as presentes atuações que o bot poderia fazer.
