### ISSUE TITLE
Documentar as sprints 9 e 10

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#272]
## Descrição da Issue
Documentar as sprints 9 e 10

## Tasks:
- [x] Documentar os resultados da sprint 9
- [x] Documentar o planejamento da sprint 9
- [x] Template dos resultados da sprint 10

## Critérios de Aceitação:
- [x] Bons documentos commitados
