### ISSUE TITLE
Implementação de US37

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#278]
## Descrição da Issue
Implementação da US37: "Eu, como usuário, desejo saber se eu preciso me vacinar"

## Tasks:
- [ ] Implementar para o bot responder corretamente
- [ ] Marcar no sheets

## Critérios de Aceitação:
- [ ] Bot responder corretamente

**Comment by AmandaNbr** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/278?planning-poker) with ZenHub @PedroLSF

**Comment by PedroLSF** [comment]
#Descrição 
Após algumas pesquisas, a US conterá informações sobre as vacinas e a ideia de que a imunidade coletiva traz a responsabilidade de que todos precisam se vacinar e para isso foram utilizados os seguintes links:
https://jornal.usp.br/artigos/o-que-e-imunidade-de-rebanho-e-quais-as-implicacoes/
https://www.gov.br/saude/pt-br/vacinacao/
