### ISSUE TITLE
Implementação da US30

### ISSUE THREAD

**Issue by kayrocesar** [fga-eps-mds/2021-1-Bot#284]
## Descrição da Issue
Implementação da US30: " Eu, como usuário, desejo saber como posso me exercitar em casa"

## Tasks:
- [x] Implementar para o bot responder corretamente
- [x] Marcar no sheets

## Critérios de Aceitação:
- [ ] Bot responder corretamente
