### ISSUE TITLE
Implementação US44

### ISSUE THREAD

**Issue by klmurussi** [fga-eps-mds/2021-1-Bot#286]
## Descrição da Issue
"Eu, como usuário, testei positivo para covid e quero saber o que fazer"

## Tasks:
- [ ] Implementar para o bot responder corretamente
- [x] Marcar no sheets

## Critérios de Aceitação:
- [ ] o bot responder corretamente
