### ISSUE TITLE
Alteração no templeate de documentação

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#295]
## Descrição da Issue
Para que o jekyll reconheça os documentos será necessario alterar o templeate de documentação.

## Tasks:
- [x] Retirar o titulo de documento.
- [x] Adicionar "cabeçalho" para o jekyll reconhecer.

## Critérios de Aceitação:
- [x] Todas alterações realizadas.
