### ISSUE TITLE
Documentação sprints 10 e 11

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#296]
## Descrição da Issue
Documentação sprints 10 e 11.

## Tasks:
- [x] Documentar os resultados da sprint 10
- [x] Documentar o planejamento da sprint 11
- [x] Template dos resultados da sprint 11

## Critérios de Aceitação:
- [x] Bons documentos commitados
