### ISSUE TITLE
Dialogar com o cliente e validar ideias de escopo

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#30]
## Descrição da Issue
Após o toró de ideias para o time definir algumas ideias de temas, a PO deverá entrar em contato com o mesmo para validar alguma ideia e deixar mais claro o que o cliente quer de fato.

## Tasks:
- [x] Comunicar os POs dos outros times sobre as ideias
- [x] Marcar e realizar reunião com o cliente
- [x] Comentar o resultado na issue

**Comment by Thais-ra** [comment]
A PO do time Capivara, Ana entrou em contato com o cliente via wpp hoje pela manhã.
Ela explicou que não daria tempo de abranger tudo, pediu pra reduzir o escopo e mostrou o quadro com os temas levantados pelo time.
O cliente pediu para englobar notícias de políticas públicas, instruções de como as prefeituras poderiam agir para reduzir o nível de contágio no seu territorio.
Ele pediu para focarmos em **prevenção, vacinas e políticas públicas** inicialmente.
Ana tentou fazer reunião com os outros POs mas só o Pedro dialogou com ela. O time PlusUltra foi atualizado sobre a conversa com o cliente.
