### ISSUE TITLE
Implementação da US40

### ISSUE THREAD

**Issue by klmurussi** [fga-eps-mds/2021-1-Bot#314]
## Descrição da Issue
Eu, como usuário, desejo saber qual a eficácia de cada vacina aprovada pela anvisa - MUST 5

## Tasks:
- [ ] Marcar na tabela "em andamento"
- [ ] Criar intent
- [ ] Criar story
- [ ] Criar action

## Critérios de Aceitação:
- [ ] Botinho respondendo a US.
- [ ] Marcar na tabela "finalizado"

**Comment by klmurussi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/314?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @LamequeFernandes @Thais-ra

**Comment by LamequeFernandes** [comment]
US40 implementada com sucesso.
