### ISSUE TITLE
Documentação das sprints 9 e 10

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#315]
## Descrição da Issue
Adicionar ao documento de gerência o planejamento e resultado das sprints 9 e 10

## Tasks:
- [ ] Planejamento e resultado da sprint 9
- [ ] Planejamento e resultado da sprint 10

## Critérios de Aceitação:
- [ ] Documentos bem feitos
- [ ] Aprovado por, pelo o menos, 1 integrante do grupo.
