### ISSUE TITLE
Reunião pre-planning da sprint 12

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#319]
## Descrição da Issue
Reunião de planejamento da release 2 e sprint 12

## Tasks:
- [ ] Determinar  o que precisa ser feito
- [ ] Começar preparação para release 2

## Critérios de Aceitação:
- [ ] Escopo final definido

**Comment by HenriqueHida** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021-1-Bot/319?planning-poker) with ZenHub @AmandaNbr @gatotabaco
