### ISSUE TITLE
Criar template de pull request

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#32]
## Descrição da Issue
Criar um template para padronizar a criação de pull requests

## Tasks:
- [x]  Idealizar um template para os pull requests
- [x] Formatação em markdown
- [x] Linguagem padrão PT-BR

**Comment by klmurussi** [comment]
[Documento].(https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/.github/PR_TEMPLATE.md) criado na pasta .github

**Comment by Bruno-Felix** [comment]
Bom Dia/ tarde/ noite

Me chamo Bruno Félix e serei um dos monitores de MDS desse semestre.

Excelente template de pull request, se bem aplicado vai dá um upp na qualidade do trabalho de voces.

Um dica boba: Coloquem "Closes #xxx" no pr para fecharem a issue em questão, caso o pr seja aceito, ex.: Closes #32

**Comment by Thais-ra** [comment]
Acrescentar a parte de testes e fazer o template aparecer na hora de criar um PR novo.

**Comment by klmurussi** [comment]
Modifiquei o nome para reconhecer na hora de um PR novo, porém o arquivo precisa estar na main
