### ISSUE TITLE
Criar pipeline de CI/CD

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#321]
## Descrição da Issue
Criar pipeline com GitHub Actions ou Travis

## Tasks:
- [x] Verificar estilo e formatação de código
- [ ] Verificação estática de código
- [x] Testes Rasa
- [ ] Testes unitários

**Comment by yudi-azvd** [comment]
Algumas outras coisas que terão que ser vistas pra esta issue:

- [ ] Ambiente de homologação
- [ ] Configuração do servidor de actions na Heroku
- [ ] ~Adicionar as imagens dos containers no Docker registry~

**Comment by AmandaNbr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/321?planning-poker) with ZenHub @yudi-azvd @Thais-ra @LuizPettengill
