### ISSUE TITLE
Terminar o GH-PG 

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#322]
## Descrição da Issue
Terminar o site do repositorio.

## Tasks:
- [ ] Correção de bugs
- [ ] Correção em direcionamentos
- [ ] Correção em menus

## Critérios de Aceitação:
- [ ] Site pronto para a R2.
