### ISSUE TITLE
Documentar as sprints 11 e 12

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#326]
## Descrição da Issue
Documentar as sprints 11 e 12

## Tasks:
- [x] Documentar os resultados da sprint 11
- [x] Documentar o planejamento da sprint 12
- [x] Template dos resultados da sprint 12

## Critérios de Aceitação:
- [x] Bons documentos commitados
