### ISSUE TITLE
Correções nas documentações da Equipe Plus Ultra

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#327]
## Descrição da Issue
Arrumar as datas de forma que o planejamento venha antes dos resultados, colocar a tag para aparecer na página certa do ghPages e arrumar tabelas com erro de formatação.

## Tasks:
- [ ] Arrumar as datas
- [ ] Inserir as tags
- [ ] Arrumar tabelas com erro de formatação

## Critérios de Aceitação:
- [ ] Todas as tasks finalizadas
