### ISSUE TITLE
Criar políticas do repositório

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#33]
## Descrição da Issue
Criar políticas do repositório para auxiliar a organização do projeto

## Tasks:
- [x] Criar política de branch
- [x] Criar política de commit

## Critérios de Aceitação:
- [x] O documentos deverá seguir o padrão de template

**Comment by Thais-ra** [comment]
Uma dica é pesquisar por repositórios de software livre e observar como é feito a politica de branch e commit.

**Comment by LamequeFernandes** [comment]
Política de commit:
https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md

**Comment by LamequeFernandes** [comment]
Política de branch:
https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md

**Comment by Thais-ra** [comment]
No documento de commits: Mudar padrão para português e adicionar um dicionário com emojis.
No documento de branches: Mudar **Master** para **Main**, mudar padrão para português e adicionar o numero da issue na branch.

**Comment by LamequeFernandes** [comment]
Mudanças realizadas.
