### ISSUE TITLE
Realizar testes nas US27 - US32

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#332]
## Descrição da Issue
Realizar testes Rasa nas US27 a US32

## Tasks:
- [x] Verificar o funcionamento das intents
- [x] Corrigir possíveis bugs

## Critérios de Aceitação:
- [x] Tudo funcionando como deveria
