### ISSUE TITLE
Realizar testes nas US11 - US15

### ISSUE THREAD

**Issue by kayrocesar** [fga-eps-mds/2021-1-Bot#333]
## Descrição da Issue
Realizar testes Rasa nas US11 a US15

## Tasks:
- [x] Verificar o funcionamento das intents
- [x] Corrigir possíveis bugs

## Critérios de Aceitação:
- [x] Tudo funcionando como deveria

**Comment by kayrocesar** [comment]
Os problemas detectados em outras  intents com a  palavra "sintomas" serão resolvidos por outro integrante .

As intenções das USs 14 e 15 precisaram ser reescritas  devido à semelhança dos termos,pois em determinadas situações as intenções eram confundidas pelo bot.
