### ISSUE TITLE
Criar ambiente de documentação - GitHub Pages

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#34]
## Descrição da Issue
Criação de ambiente com Github Pages para registrar documentos do projeto

## Tasks:
- [x] Criar Github Pages
- [x] Comentar na issue com o link

## Critérios de Aceitação:
- [x] Deve ser acessível pelo link do github io

**Comment by LamequeFernandes** [comment]
Tema e estrutura do github pages:
https://fga-eps-mds.github.io/2021-1-Bot/
