### ISSUE TITLE
Humanização e revisão das US 22 até 31

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#344]
## Descrição da Issue
Humanizar e revisar as US 22 até a US 31 

## Tasks:
- [ ] Humanizar as US
- [ ] Revisar as US

## Critérios de Aceitação:
- [ ] Aceito por, pelo o menos, 1 integrante do grupo

**Comment by AmandaNbr** [comment]
Falta o estimate

**Comment by HenriqueHida** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021-1-Bot/344?planning-poker) with ZenHub @kayrocesar
