### ISSUE TITLE
Comentar e organizar o arquivo test_stories

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#364]
## Descrição da Issue
Comentar a US correspondente na frente de cada teste do arquivo "test_stories", e colocá-los na ordem, para fins de organização.

## Tasks:
- [x] Fazer os comentários do número da US
- [x] Organizar testes de acordo com o número da US correspondente.

## Critérios de Aceitação:
- [x] Comentários feitos
- [x] Testes organizados de acordo com o número da US correspondente.
