### ISSUE TITLE
Documentação sprints 12 e 13

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#368]
## Descrição da Issue
Documentar sprints 12 e 13

## Tasks:
- [x] Melhorar a documentação do planejamento da sprint 12
- [x] Documentar os resultados da sprint 12
- [x] Documentar o planejamento da sprint 13
- [x] Template dos resultados da sprint 13

## Critérios de Aceitação:
- [x] Bons documentos commitados
