### ISSUE TITLE
Fazer os roteiros dos vídeos

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#369]
## Descrição da Issue
Se juntar no discord e fazer os roteiros dos vídeos das equipes e do vídeo geral.

## Tasks:
- [x] Roteiro dos vídeos das equipes
- [x] Roteiro do vídeo geral

## Critérios de Aceitação:
- [x] Enviar no grupo depois para todos ver
- [x] Roteiros bons que englobem todos os pontos a serem falados nos vídeos

**Comment by AmandaNbr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021.1-AlligaBot/369?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @PedroLSF
