### ISSUE TITLE
Ajustes finais para a R2 no github-pages

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#370]
## Descrição da Issue
Ajustes finais no github-pages.

## Tasks:
- [x] Mudar o nome do repositorio de 2021-1-Bot para 2021.1-Alligabot.
- [x] Atualizar todos os documentos que possuem o nome do repositorio antigo.
- [x] Link na foto de perfil do membros das equipes.
- [x] Pagina principal falando o que é o bot e link pro repositorio.
- [x] Subdividir o menu principal em Documentações e Politicas.

## Critérios de Aceitação:
- [x] Gh-pg pronto para a R2.

**Comment by LamequeFernandes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021.1-AlligaBot/370?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @klmurussi @Thais-ra

**Comment by LamequeFernandes** [comment]
depois de muita luta e sofrimento, deu certo.
