### ISSUE TITLE
US 01 - FAQ espaços abertos

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2021-1-Bot#38]
## Descrição da Issue
Eu, como cidadão brasileiro, quero saber de dicas de prevenção em epaços abertos, para que eu possa me sentir seguro nesses locais.

## Tasks:
- [ ] Criar a intenção de perguntar sobre prevencao ao ar livre
- [ ] Colocar a opção dessa info no menu principal do bot
- [ ] Escrever a resposta corrata com a inforção
- [ ] colocar as stories do bot

## Critérios de Aceitação:
- [ ] O treinamento do bot acontecer sem erros
- [ ] Bot testado com essa nova informação
