### ISSUE TITLE
Documentar as sprints 11 e 12 

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#385]
## Descrição da Issue
Documentar o planejamento e resultado das sprints 11 e 12.

## Tasks:
- [x] Planejamento e resultado da sprint 11.
- [x] Planejamento e resultado da sprint 12.

## Critérios de Aceitação:
- [x] Documentos bem feitos.
- [x] Revisados por, pelo menos, 1 membro do grupo.

**Comment by HenriqueHida** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021.1-AlligaBot/385?planning-poker) with ZenHub @kayrocesar
