### ISSUE TITLE
Gravar vídeo da equipe Plus Ultra

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#388]
## Descrição da Issue
Gravar vídeos dos integrantes da equipe Plus Ultra

## Tasks:
- [x] Vídeo da Amanda
- [x] Vídeo do Erick
- [x] Vídeo do Douglas
- [x] Vídeo do Pedro
- [x] Vídeo do Victor
- [x] Vídeo do Yudi

## Critérios de Aceitação:
- [x] Bons vídeos individuais
