### ISSUE TITLE
Alterar o nome de todos os documentos de gerência

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#389]
## Descrição da Issue
O nome de todos os documentos de gerência devem ser renomeados conforme padrão estabelecido.

## Tasks:
- [x] Documentos Slowbros renomeados
- [x] Documentos PlusUltra renomeados
- [x] Documentos Capivaras renomeados

## Critérios de aceitação

- [x] Documentos renomeados com sucesso

**Comment by gatotabaco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021.1-AlligaBot/389?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @klmurussi @LamequeFernandes @Thais-ra

**Comment by AmandaNbr** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021.1-AlligaBot/389?planning-poker) with ZenHub @HenriqueHida
