### ISSUE TITLE
Concretização dos primeiros passos

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#40]
## Descrição
Avançar e concretizar o trabalho como PO, a sprint tem por ideia desenvolver esses trabalhos.

## Tasks:
- [x] Entender o framework Moscow.
- [x] Marcar uma reunião para levantar ideias sobre as "epics" da equipe Plus Ultra
- [x] Realizar a reunião
- [x] Anotar as ideias

## Critérios de Aceitação:
- [x] Aprovação da equipe Plus Ultra
- [x] Ter um quadro ou um documento primário sobre os requisitos

**Comment by PedroLSF** [comment]
#Descrição
Foi feita uma reunião com toda a equipe Plus Ultra, onde levantamos foram levantas ideias em um quadro no miro sobre quais serão as "Epics", "Features" e "Estórias". Será trabalhado em um documento mais detalhado e organizado para concretizar as ideias escritas.

**Comment by Bruno-Felix** [comment]
Olá 

Me chamo Bruno e sou um dos monitores deste semestre.

Vi que inseriu a label Epic nesta issue. Cuidado, seria interessante usar somente nas Epic vindas do Product Backlog, a rastreabilidade fica melhor.

**Comment by PedroLSF** [comment]
#Descrição
Aqui está um documento para entender melhor algumas ideias levantadas pela equipe plus ultra, e assim nosso arquiteto poderá ter algo mais concreto para começar a trabalhar
[Uploading Plus Ultra (1).pdf…]()
