### ISSUE TITLE
Gravar vídeo da equipe Slowbros

### ISSUE THREAD

**Issue by kayrocesar** [fga-eps-mds/2021-1-Bot#400]
## Descrição da Issue

Gravar vídeo com os  integrantes da equipe Slowbros

## Tasks:
- [x] Vídeo com os membros participantes da equipe

## Critérios de Aceitação:
- [x] Participação Henrique Hida
- [x] Participação Kayro César
- [x] A gravação está com uma boa qualidade

**Comment by kayrocesar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021.1-AlligaBot/400?planning-poker) with ZenHub @HenriqueHida
