### ISSUE TITLE
Gravação do vídeo geral

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#404]
## Descrição da Issue
Gravação do vídeo geral

## Tasks:
- [x] Vídeos da Ana
- [x] Vídeos do Henrique
- [x] Vídeos do Pedro
- [x] Vídeo do bot

## Critérios de Aceitação:
- [x] Bons vídeos individuais

**Comment by AmandaNbr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021.1-AlligaBot/404?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @PedroLSF @HenriqueHida
