### ISSUE TITLE
Avanço em noções da arquitetura do projeto

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#41]
## Descrição da Issue
Nesta issue meu objetivo será criar uma noção menos abstrata de como será arquitetura final do projeto, principalmente com relação a frameworks, API's e integração com plataformas.

## Tasks:
- [x] Estudar como o bot obtém os dados do site
- [x] Estudar sobre a integração com API/plataformas, e Rasa
- [x] Avançar na arquitetura
 
## Critérios de Aceitação:
- [x] Entender como é feita a integração de um chatbot com as plataforma Telegram
- [x] Entender o funcionamento do Rasa
- [x] Ter noções menos abstratas de como será a arquitetura final do projeto
- [x] Montar um desenho inicial da arquitetura do bot, com relação ao tema do grupo (prevenção)

**Comment by victorear05** [comment]
A integração do rasa com o telegram é facilmente feita usando o BotPai do telegram e obtendo as credenciais, e após colocando-a no bot rasa já criado, via prompt de comando mesmo, no link abaixo tem a devida explicação:
https://rasa.com/docs/rasa/connectors/telegram
A plataforma telegram deve ter um acesso menor, quando comparado com outras plataformas, como por exemplo o WhatsApp, ou Facebook Messenger, porém é disponibilizada pelo próprio telegram de forma gratuita e fácil.

**Comment by victorear05** [comment]
A criação de um bot com o Rasa pode ser feita a partir do prompt, após ser feita a instalação do rasa na máquina, os comandos para ele podem ser encontrados em:
https://rasa.com/docs/rasa/command-line-interface

**Comment by victorear05** [comment]
Consegui fazer tudo o que eu tinha previsto para essa sprint, ao final consegui ter uma boa noção do que o rasa, como ele funciona e como o usar, além disso pesquisei a integração desde com a plataforma telegram. Após isso montei um fluxograma bem básico, com base nos épicos e nas features decididas pelo grupo em reunião. O fluxograma citado possui os temas relacionados a prevenção que nós como grupo 1 pretendemos abordar, e de quais links serão extraídas essas informações. Abaixo segue tal fluxograma:
![Fluxograma ChatBot-Atualizado](https://user-images.githubusercontent.com/78758172/129460691-61bdd9d6-33fb-4fb0-843a-37e229f7679e.png)
