### ISSUE TITLE
Editar vídeo da Release 2

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#420]
## Descrição da Issue
Editar vídeo de apresentação da equipe Slowbros para a release 2.

## Tasks:
- [x] Editar vídeo de apresentação.
- [x] Fazer upload pro Youtube.

## Critérios de Aceitação:
- [x] Vídeo aprovado por, pelo o menos, 1 integrante do grupo.

**Comment by HenriqueHida** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021.1-AlligaBot/420?planning-poker) with ZenHub @kayrocesar
