### ISSUE TITLE
Documentar gerência da sprint 13

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#424]
## Descrição da Issue
Planejamento e resultado da sprint 13

## Tasks:
- [ ] Planejamento da sprint 13
- [ ] Resultado da sprint 13

## Critérios de Aceitação:
- [ ] Documentos bem feitos

**Comment by HenriqueHida** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SlowbrosZH-614b7ea6f77eaf001d75430c/issues/fga-eps-mds/2021.1-AlligaBot/424?planning-poker) with ZenHub @kayrocesar
