### ISSUE TITLE
Subir imagens de todos os gráficos de gerencia

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#428]
## Descrição da Issue
É necessário criar uma branch para subir todos os gráficos de gerência de maneira que seja possível reverter mais facilmente os erros.

## Tasks:
- [x] Velocity, conhecimento, health check e burndown sprint 8
- [x] Velocity, conhecimento, health check e burndown sprint 9
- [x] Velocity, conhecimento, health check e burndown sprint 10
- [x] Velocity, conhecimento, health check e burndown sprint 11
- [x] Velocity, conhecimento, health check e burndown sprint 12
- [x] Velocity, conhecimento, health check e burndown sprint 13

## Critérios de Aceitação:
- [x] Todas as imagens foram upadas em commits de quatro em quatro imagens (por sprint)

**Comment by gatotabaco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021.1-AlligaBot/428?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @klmurussi @LamequeFernandes @Thais-ra
