### ISSUE TITLE
Update no repositório do projeto e documentação

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#43]
## Descrição da Issue
Nessa sprint continuarei na parte das documentações, falando com os outros scrum masters e dividindo quais são gerais e quais são para a equipe, e também tentarei dar uma cara melhor para o repositório.

## Tasks:
- [x] Entrar em contato com os outros scrum masters.
- [x] Tentar definir com os sm o escopo do que é parte do grupo e o que é parte do projeto .
- [x] Mudar o readMe do projeto.
- [x] Mudar a descrição do projeto.
- [ ] Deixar o git de acordo com o que se pede para estar apresentável como opensource.
- [x] Configurar o ambiente na máquina segundo o docker.

## Critérios de Aceitação:
- [x] Saber qual documentação é geral e qual é por equipe.
- [ ] Repositório arrumado.

**Comment by Bruno-Felix** [comment]
Olá Sou Bruno, um dos monitores da matéria.

Uma dica de task seria inserir no About da home do rep o link da sua gh page, ok ainda n~ao está sendo desenvolvida, mas é algo comum entrar num rep e ter lá o link pra gh page do projeto.

Vi a task de definição do que é doc geral e doc de equipe, após isso talves seria interessante já puxar pra gh page a documentação e pensar na estrutura(logica da side bar e navegação) que vcs irão trabalhar.

Na ultima task, se conseguirem dar check em todos os pontos da Community profile seria bem interessante.
![Captura de tela de 2021-08-14 23-00-25](https://user-images.githubusercontent.com/38890440/129464583-0ff394e6-92a3-48bb-b57f-4764195451c6.png)

**Comment by Bruno-Felix** [comment]
Um ponto que entra um pouco em documentação e faz parte da avaliação de vcs é a questão do planning poker.

Trabalhem com isso no planning, é bom para gerar gráficos de trabalho no final da sprint e comparar com a passada pra ver se melhorara ou não, e fazer ajustes pra proxima.

Zenhub é bom pra isso. Comecem o quanto antes a pontuar suar issues.

**Comment by AmandaNbr** [comment]
Obrigada pela ajuda, Bruno!
Eu tenho a seguinte duvida sobre o gh pages, pode ter mais de um gh page por repositório? Aí quando alguém entrasse no rep do projeto poderia acessar cada um dos gh pages de cada equipe?

**Comment by Bruno-Felix** [comment]
> Obrigada pela ajuda, Bruno!
> Eu tenho a seguinte duvida sobre o gh pages, pode ter mais de um gh page por repositório? Aí quando alguém entrasse no rep do projeto poderia acessar cada um dos gh pages de cada equipe?

Taí uma boa pergunta.

Nunca vi 3 gh pages.

Acredito que não tenha como isso.

**Comment by AmandaNbr** [comment]
As tarefas de organização do repositório de acordo com a checklist de open source não puderam ser finalizadas devido a data da reunião com os scrum masters que coincidiu com o fim da sprint, e foram, portanto, remanejadas para a próxima sprint.
