### ISSUE TITLE
Avançar na introdução de Docker no projeto com Dockerfile e docker-compose

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#44]
## Tasks:
- [x] Dockerfile para o bot
- [x] docker-compose para o bot

## Critérios de Aceitação:
- [x] [devops.md](https://github.com/fga-eps-mds/2021-1-Bot/blob/init-devops/devops.md) atualizado com as instruções do docker/docker-compose
- [ ] Aceitação dos outros de DevOps

**Comment by yudi-azvd** [comment]
Não consegui fazer essa semana. Vou colocar pra semana que vem.
