### ISSUE TITLE
Alteração na politica de Brach

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#47]
## Descrição da Issue
Adição da explicação sobre a brach develops na politica de Brach.

## Tasks:
- [x] Adição da explicação sobre a brach develops.
- [x] Comentar na issue com o link.

## Critérios de Aceitação:
- [x]  Deve ser acessível pelo link do github io

**Comment by LamequeFernandes** [comment]
Adição realizada!
