### ISSUE TITLE
Criar protótipo de baixa fidelidade (time plus-ultra)

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#56]
## Descrição da Issue
A partir da reunião de brainstorm do protótipo de baixa fidelidade de fluxo de conversa com o bot (da parte do Time Plus-Ultra), a ser realizada no domingo, 12:50

## Tasks:
- [x] Fazer a primeira versão do protótipo de baixa fidelidade
- [x] Documentar a reunião de brainstorm do protótipo de baixa fidelidade de fluxo de conversa com o bot

## Critérios de Aceitação:
- [x] Criação de um fluxograma para o protótipo de baixa fidelidade do time Plus-Ultra

**Comment by victorear05** [comment]
Fluxo de conversas do time PlusUltra com o tema prevenção:
![Captura de tela de 2021-08-25 09-37-02](https://user-images.githubusercontent.com/78758172/130791709-7227e775-a5e3-4413-82a7-f94e5a15977b.png)
Link de acesso para esse fluxo, juntamente com os links das fontes de onde serão obtidas as informações:
https://miro.com/welcomeonboard/Z1BnWXhWbW5COE5RczhVb1NReHlsSktoVlYxZFlPMldqSmVITG52MTlWcEoxY1F5bmJ0WElWN2g1VmZCdW81WXwzMDc0NDU3MzYxNTgyMzg5MTUx
