### ISSUE TITLE
Estruturação do documento de arquitetura

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#57]
## Descrição da Issue
Nessa sprint nós arquitetos decidimos estruturar melhor o documento de arquitetura, pesquisando sobre o banco de dados a ser utilizado, e também fazer, ou iniciar o fluxo de conversas do bot.

## Tasks:
- [x] Juntar todas as possíveis respostas do bot (time SlowBros) e um fluxo de conversa (intenção/ação(resposta))
- [x] Juntar todas as possíveis respostas do bot (time Capivara) e um fluxo de conversa (intenção/ação(resposta))
- [x] Juntar todas as possíveis respostas do bot (time PlusUltra) e um fluxo de conversa (intenção/ação(resposta))
- [x] Definir um banco de dados, ou ver como é armazenada as respostas do RasaBot
- [x] Fazer uma representação arquitetural 
## Critérios de Aceitação:
- [x] Update de informações relevantes no documento de arquitetura
- [x] Desenho de arquitetura feito (pelo menos de modo inicial)

**Comment by klmurussi** [comment]
Reunião 19/08:
Presentes: @klmurussi @victorear05 

Decidimos que na R1 começaremos a trabalhar com o bot no telegram, mas só respondendo perguntas básicas, como "o que é covid-19?" "como me previnir?" "como a pfzier funciona?"

Pesquisar também se o Rasa guarda essas informações ou precisaremos de um banco de dados
