### ISSUE TITLE
Reunião dos Scrum Masters para alinhar documentação

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#58]
## Descrição da Issue
Essa reunião tem como intuito alinhar o trabalho das 3 equipes quanto a documentos e templates que devem estar prontos para a release 1.

## Tasks:
- [x] Acontecer a reunião com todos os SM presentes
- [x] Conseguir ter o entendimento de cada documento necessário para a release e como ele se encaixa (se deve ser feito por cada equipe ou um documento só para todo projeto)

## Critérios de Aceitação:
- [x] Tarefa total ou parcialmente concluída

**Comment by HenriqueHida** [comment]
Os documentos são:  

- Issue template do termo de abertura > @LamequeFernandes
- Definir ferramenta para o fluxograma da estrutura analítica > @AmandaNbr 
- Readme > @HenriqueHida 
- Documento de Visão.
- Documento de arquitetura.
- Guia de Estilo e identidade visual.
- RoadMap.
