### ISSUE TITLE
Documentação da Estrutura Analítica do projeto

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#59]
## Descrição da Issue
Abertura da primeira versão do documento da Estrutura Analítica do projeto que será realizado pelos scrum masters.

## Tasks:
- [x] Definir a ferramenta a ser utilizada na criação da estrutura analítica.
- [x] Coleta de dados e conhecimentos necessários para a criação de um bom documento.
- [x] Criar a primeira versão do documento.
- [x] Enviar para a main

## Critérios de Aceitação:
- [x] Um documento que exponha bem a estrutura do projeto.

**Comment by HenriqueHida** [comment]
Uma ferramenta que, na minha opinião, seria uma boa escolha para a criação da estrutura analítica seria a [Lucidchart](https://www.lucidchart.com/pages/pt)

**Comment by gatotabaco** [comment]
> Uma ferramenta que, na minha opinião, seria uma boa escolha para a criação da estrutura analítica seria a [Lucidchart](https://www.lucidchart.com/pages/pt)

Gostei dessa ferramenta. Estou disposto a trabalhar nela.

**Comment by AmandaNbr** [comment]
Eu também gosto do [Miro,](https://miro.com/app/dashboard/) a gente pode decidir entre os dois!

**Comment by gatotabaco** [comment]
![ChatBot](https://user-images.githubusercontent.com/54778783/130526304-44c5f133-c2d3-4098-90ab-a8d7b517f003.png)
