### ISSUE TITLE
Documentação das features e do roadmap

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#60]
## Descrição da Issue
Documentar as atividades feitas na sprint 1 e 2

## Tasks:
- [ ] Documentar as Features
- [ ] Documentar o Roadmap

## Critérios de Aceitação:
- [ ] Ter as features documentadas
- [ ] Aprovação da equipe Plus Ultra
