### ISSUE TITLE
Documentação das sprints

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#62]
## Descrição da Issue
Fazer os documentos de planejamento e resultados para cada sprint que ja ocorreu.

## Tasks:
- [x] Documento de planejamento da sprint 0
- [x] Documento de resultados da sprint 0
- [x] Documento de planejamento da sprint 1
- [x] Documento de resultados da sprint 1
- [x] Documento de planejamento da sprint 2
- [x] Documento de resultados da sprint 2
- [x] Documento de planejamento da sprint 3
- [x] Documento de resultados da sprint 3

## Critérios de Aceitação:
- [x] Documentos bem organizados e explicando bem sobre cada sprint.
