### ISSUE TITLE
Criação e formatação do GHPages

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#63]
## Descrição da Issue
Criar e começar a colocar os tópicos de documentação principais. Também decidir como organizar o GHPages em função das 3 equipes.

## Tasks:
- [x] Criar o GHPages.
- [x] Estudar sobre formatação.
- [x] Criar o menu de navegação
- [x] Criar o menu lateral de seleção de documento para visualização

## Critérios de Aceitação:
- [x] Uma página criada já com alguns tópicos de documentos.
