### ISSUE TITLE
Backlog versão inicial

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#65]
## Descrição da Issue
Será desenvolvido uma versão inicial do product backlog do bot.

## Tasks:
- [x] Documentação das Epics/Features seguindo o template.
- [x] Organização das Epics/Features por ordem de prioridade.

## Critérios de Aceitação:
- [x] Aprovação de algum membro.
- [x] Preencher a versão corretamente.
