### ISSUE TITLE
Estruturar GitHub Pages

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#66]
## Descrição da Issue
Estruturar GitHub Pages

## Tasks:
- [ ] Criar menu no GitHub pages.
- [ ] Subir documentações para o pages.
- [ ] Subir templeates para o pages.

## Critérios de Aceitação:
- [ ] Página com as documentações da sprint 0 à sprint 3.
