### ISSUE TITLE
Reunião com os integrantes para discutir os requisitos e o backlog do produto

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#70]
## Descrição da Issue
Realizar uma reunião com o objetivo de definir os requisitos do produto.

## Tasks:
- [x] Marcar a reunião.
- [x] Anotar os requisitos definitos.

## Critérios de Aceitação:
- [x] Ter a primeira versão dos requisitos do projeto.
- [ ] Mostrar aos outros grupos para aprovação e possíveis mudanças.

**Comment by AmandaNbr** [comment]
Em um primeiro momento, o resultado do brainstorm dos requisitos ficou da seguinte maneira:
![image](https://user-images.githubusercontent.com/44625056/130338574-cb7f6739-dcc1-4cac-8c64-2023e58ecfc0.png)
