### ISSUE TITLE
Correção na politica de branch

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#77]
## Descrição da Issue
Em algumas partes da política de branch o texto está meio confuso ou de difícil compreensão. Então optamos por corrigir isto.

## Tasks:
- [ ] Retirar os "/" da frente dos prefixos na parte em que são citados.
- [ ] Trocas os ":" por "/" na parte em que é apresentado o formado.
- [ ] Informar que o assunto sempre deve estar em letras minusculas.

## Critérios de Aceitação:
- [ ] Que todo os membros do grupo estejam de acordo com as mudanças.
