### ISSUE TITLE
Conversando com o bot pelo telegram

### ISSUE THREAD

**Issue by Ericklevy** [fga-eps-mds/2021-1-Bot#83]
## Descrição da Issue
O integrante @DouglasMonteles criou e interagiu com o bot pelo Telegram

## Tasks:
- [x] Instalar o Rasa localmente
- [x] Descobrir como liberar o localhost para acesso externo
- [x] Cadastrar as credenciais do bot do telegram no projeto Rasa
- [x] Interagir com o bot em mensagens em português
- [x] Conversando com o bot pelo telegram

**Comment by DouglasMonteles** [comment]
O projeto foi adicionado ao GitHub na branch  rasa-training, lá está especificado como instalar e executar o projeto de uma assistente feita em Rasa e interagir com ele pelo chat do Telegram
