### ISSUE TITLE
Criação do protótipo de baixa fidelidade do ghPages

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#88]
## Descrição da Issue
O objetivo dessa issue é levantar protótipo de baixa fidelidade do ghPages.

## Tasks:
- [ ] Realizar o protótipo de baixa fidelidade do ghPages.
- [ ] Comentar na issue uma foto do protótipo.

## Critérios de Aceitação:
- [ ] Aceitação dos membros das equipes

**Comment by AmandaNbr** [comment]
Criei um protótipo de uma ideia de formatação do ghPages do repositório.
Já que será só um para as 3 equipes eu acho que seria interessante ter uma barra horizontal superior onde dê pra navegar entre home/principal, que é onde vão ficar os documentos gerais (termo de abertura, etc), e cada equipe, onde vão ficar os documentos específicos (documentação das sprints, etc).
![](https://user-images.githubusercontent.com/44625056/130683763-f8815ba5-bed5-4744-99ab-e12525485b8d.png)
*só está mostrando indo da principal pras paginas da Equipe Plus Ultra e da Equipe Capivaras, mas era pra ter a Equipe Slowbros também, só que eu atingi o limite de uso do lucidchart, então ficou assim.

Exemplo de inspiração: https://fga-eps-mds.github.io/2019.2-Acacia/#/
