### ISSUE TITLE
Estruturar, fazer update das politicas e de toda documentação já realizada no GHPages

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#95]
## Descrição da Issue
Deixar o GHPges pronto(ou quase) para a R1

## Tasks:
- [x] Estrutura do GHPages.
- [x] Update das politicas no pages.
- [x] Update das documentações no pages.
- [x] Criar uma parte para identificar os times(quem somos).

## Critérios de Aceitação:
- [x] Documentações da sprint 0 à sprint 4 no ghpages.
- [x] Politicas de commit e branch no ghpages.
- [x] Quem somos no ghpages.

**Comment by gatotabaco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/95?planning-poker) with ZenHub @LamequeFernandes @Thais-ra @klmurussi @AnaCarolinaRodriguesLeite @MegahNevel
