### ISSUE TITLE
Reunião dos Scrum Masters e Product Owners

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#96]
## Descrição da Issue
Reunião para designarmos as tarefas restantes para a release 1

## Tasks:
- [x] Realização da reunião com os PO e SM de todas as equipes.

## Critérios de Aceitação:
- [x] Fazer uma justa divisão de tarefas
- [x] Aprovação dos integrantes da reunião
