### ISSUE TITLE
Melhorar README.md do projeto

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#98]
## Descrição da Issue
Melhorar o README.md com as informações que temos até agora, deixando-o com menos cara de template.

## Tasks:
- [x] Adicionar instruções para montar o ambiente de desenvolvimento com Docker (o sucesso do cumprimento dessas instruções depende do merge da branch `init-devops`)
- [x] Melhorar a seção dos desenvolvedores com tabela e fotos
- [x] Revisão geral do documento
- [x] Apagar seções que ainda faltam (elas vão voltar no tempo certo)
- [x] Colocar logo do projeto
- [x] Adicionar guia de contribuição #107 

## Critérios de Aceitação:
- [x] README.md atualizado
- [x] Aceitação dos assignees e de uma terceira pessoa

**Comment by gatotabaco** [comment]
Primeira versão do [Guia de contribuição](https://github.com/fga-eps-mds/2021-1-Bot/blob/main/docs/contribuir.md) criada e adicionada a Main
