### ISSUE TITLE
Escolher um padrão de estilo de código

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#99]
## Descrição da Issue
Escolher um padrão de estilo de código.

## Tasks:
- [x] Dar uma olhada nos padrões mais populares de estilo de código para Python
- [x] Um texto curto na documentação apresentando o estilo escolhido
- [x] Linkar no documento de contribuição?
- [x] Pesquisar por ferramentas de automação e imposição de padrão de estilo de código

## Critérios de Aceitação:
- [x] Avaliação de alguns tecnologistas

**Comment by yudi-azvd** [comment]
Achei depois de umas pesquisas :

Formatadores: [autopep8](https://pypi.org/project/autopep8/), [Black](https://black.readthedocs.io/en/stable/)

Linter para estilo de código: [Flake8](https://flake8.pycqa.org/en/latest/)

Integração com VSCode parece tranquilo. É só definir um `.flake8` com as configurações para estilo. Tenho que ver se ainda vai funcionar com container e como tudo isso vai ser garantido no pipeline de CI/CD

**Comment by yudi-azvd** [comment]
No final acabei escolhendo autopep8 por ter formatação automática
